reborns = {
    "Banana Split Upgrader": {"Life": 0, "Rarity": 5},
    "Nature's Grip": {"Life": 0, "Rarity": 15},
    "Quantum Ore Cleaner": {"Life": 0, "Rarity": 15},        
    "Massive Diamond Mine": {"Life": 0, "Rarity": 15},       
    "Frozen Justice": {"Life": 0, "Rarity": 15},
    "Industrial Firecrystal Mine": {"Life": 0, "Rarity": 15},
    "Sage Redeemer": {"Life": 0, "Rarity": 15},
    "Pizza Blaster": {"Life": 0, "Rarity": 15},
    "Astral Predictor": {"Life": 0, "Rarity": 15},
    "Vortex Chamber": {"Life": 0, "Rarity": 15},
    "Wild Spore": {"Life": 0, "Rarity": 17},
    "Righteous Will": {"Life": 5, "Rarity": 6},
    "Ancient Temple": {"Life": 5, "Rarity": 7},
    "Ore Sawmill": {"Life": 5, "Rarity": 10},
    "The Catalyst": {"Life": 5, "Rarity": 12},
    "Azure Refiner": {"Life": 5, "Rarity": 15},
    "Ore Illuminator": {"Life": 5, "Rarity": 15},
    "Flaming Schrodinger": {"Life": 5, "Rarity": 16},
    "Venomshank": {"Life": 5, "Rarity": 3},
    "Tesla Resetter": {"Life": 10, "Rarity": 18},
    "Yunium Mine": {"Life": 10, "Rarity": 17},
    "Big Bad Blaster": {"Life": 10, "Rarity": 18},
    "Mineral Wheel": {"Life": 10, "Rarity": 17},
    "Clockwork": {"Life": 10, "Rarity": 8},
    "Dreamer's Might": {"Life": 20, "Rarity": 15},
    "Big Bertha": {"Life": 20, "Rarity": 19},
    "Scorpium Mine": {"Life": 20, "Rarity": 17},
    "Newtonium Mine": {"Life": 20, "Rarity": 18},
    "Dreamer's Fright": {"Life": 20, "Rarity": 18},
    "Plasma Scanner": {"Life": 20, "Rarity": 19},
    "Lightningbolt Refiner": {"Life": 20, "Rarity": 18},
    "Green Tea Latte": {"Life": 20, "Rarity": 10},
    "Scorching Heat": {"Life": 20, "Rarity": 10},
    "The Fracture": {"Life": 20, "Rarity": 4},
    "Solar Flare": {"Life": 50, "Rarity": 18},
    "Atomium Mine": {"Life": 100, "Rarity": 12},
    "Dark Magic": {"Life": 100, "Rarity": 18},
    "Eternal Journey": {"Life": 100, "Rarity": 10},
    "Toxic Waste Disposal": {"Life": 100, "Rarity": 13},
    "Blind Justice": {"Life": 100, "Rarity": 7},
    "Cooling Chamber": {"Life": 100, "Rarity": 8},
    "Atlantic Monolith": {"Life": 100, "Rarity": 10},
    "Dragonglass Mine": {"Life": 100, "Rarity": 8},
    "Gate of Eclipse": {"Life": 100, "Rarity": 15},
    "Timeless Enhancement": {"Life": 150, "Rarity": 7},
    "Ambrosia Fountain": {"Life": 150, "Rarity": 7},
    "Dreamer's Anguish": {"Life": 200, "Rarity": 3},
    "Phase Refiner": {"Life": 200, "Rarity": 7},
    "Pilotite Mine": {"Life": 200, "Rarity": 13},
    "Guardian of the Gate": {"Life": 250, "Rarity": 5},
    "Morning Star": {"Life": 250, "Rarity": 14},
    "Aether Refinery": {"Life": 300, "Rarity": 5},
    "Symmetrium Mine": {"Life": 300, "Rarity": 10},
    "Sakura Garden": {"Life": 350, "Rarity": 3},
    "Invasive Cyberlord": {"Life": 400, "Rarity": 10},
    "The Sporest": {"Life": 400, "Rarity": 8},
    "Nuclear Stronghold": {"Life": 400, "Rarity": 7},
    "Phase Processor": {"Life": 450, "Rarity": 7},
    "Breech Loader": {"Life": 500, "Rarity": 8},
    "The Abomination": {"Life": 500, "Rarity": 8},
    "Crystalized System": {"Life": 600, "Rarity": 12},
    "Fractured Reality": {"Life": 750, "Rarity": 5},
    "Ore Skillet": {"Life": 753, "Rarity": 11},
    "Gravitational Gearwork": {"Life": 800, "Rarity": 13},
    "Shard Park": {"Life": 800, "Rarity": 9},
    "Newtonic Corroder": {"Life": 1000, "Rarity": 10},
    "Red Giant": {"Life": 1000, "Rarity": 14},
    "Skyliner Flux": {"Life": 1000, "Rarity": 7},
    "Industrial Scarab": {"Life": 5000, "Rarity": 3},
    "Desert Monument": {"Life": 7300, "Rarity": 1}
}

advanced_reborns = {
    "Dragon Blaster": {"Life": 500, "Rarity": 3},
    "Frigid Dystopia": {"Life": 500, "Rarity": 3},
    "Precursor Furnace": {"Life": 500, "Rarity": 3},
    "Precursor Mine": {"Life": 500, "Rarity": 3},
    "Vampire Spore": {"Life": 500, "Rarity": 1},
    "Vulcan's Grasp": {"Life": 500, "Rarity": 1},
    "Stardust Pulsar": {"Life": 600, "Rarity": 2},
    "Hades' Palace": {"Life": 666, "Rarity": 3},
    "Sword God Shrine": {"Life": 800, "Rarity": 1},
    "Igneous Forge": {"Life": 1000, "Rarity": 3},
    "Virtual Enhancer": {"Life": 1000, "Rarity": 3},
    "Palladium Drill": {"Life": 1000, "Rarity": 2},
    "Father of Freon": {"Life": 1000, "Rarity": 2},
    "Northern Lights": {"Life": 2000, "Rarity": 1},
    "Arcane Lightning": {"Life": 2000, "Rarity": 3},
    "Black Dwarf": {"Life": 2000, "Rarity": 3},
    "Dreamer's Blight": {"Life": 2000, "Rarity": 2},
    "Big Alberto": {"Life": 2000, "Rarity": 3},
    "Crystal Shrine": {"Life": 3000, "Rarity": 1},
    "Son of Poison": {"Life": 3000, "Rarity": 2},
    "Spirit of Fire": {"Life": 3000, "Rarity": 2},
    "Nova Star": {"Life": 5000, "Rarity": 3},
    "Apollium Mine": {"Life": 5000, "Rarity": 1},
    "Railgun Cannon": {"Life": 8000, "Rarity": 2},
    "Blue Supergiant": {"Life": 10000, "Rarity": 2}
}